#!/bin/sh

# Executable Location
set EXEC = "/home/tsk/Documents/GitHub/PAR2D/FV/cmake-arch/MPI2DFV"

# Case Parameters
set N = 8

/home/tsk/Documents/GitHub/PAR2D/FV/cmake-arch/MPI2DFV < cone.in |& tee out.log
