#!/bin/bash

exec=/home/mpiusr/hyades_nfs/PAR2D/FV/cmake-build/MPI2DFV

#opts='-ts_monitor -info -options_view -check_pointer_intensity 0 -view_initial_residual -on_error_attach_debugger'

opts_exp='-options_view -check_pointer_intensity 0 -on_error_attach_debugger
      -ts_view -snes_monitor_residual
      -ts_type rk 3 -ts_max_time 1.0e-3
      -log_view'

opts_imp='-options_view -check_pointer_intensity 0 -on_error_attach_debugger
          -ts_view -ts_type beuler -ts_max_time 1.0e-2
	  -ksp_type gmres -ksp_gmres_restart 20 -pc_type ilu
	  -ksp_rtol 0.01 -ksp_monitor_cancel
	  -snes_rtol 0.0001
	  -snes_mf -snes_monitor_cancel 
	  -snes_type newtonls -ts_max_snes_failures 30
	  -snes_linesearch_type bisection
	  -log_view
	  '
	  #-npc_snes_type qn
	  #-ksp_type fgmres -pc_type ilu
	  # -snes_type newtonls -ts_max_snes_failures 30

mpirun -s all -n 8 $exec $opts_imp < test.in |& tee out.log
